### ISSUE TITLE
Add Ramon Miranda's "Concept Design" brushes to repository

### ISSUE THREAD

**Issue by AtsusaKaneytza** [Jehan/mypaint-brushes#2]
Originally mentioned here:
https://github.com/mypaint/mypaint/issues/842#issuecomment-338114389

Brush Download Location:
https://theshock.deviantart.com/art/Concept-Design-Brushes-MyPaint-256920749

**Comment by Jehan** [comment]
Hi!

The `mypaint-brush` package is now officially at: https://github.com/mypaint/mypaint-brushes/

You are welcome to make again your request for brush adding there, if you still want. Unfortunately I also see that the link is now dead (the page is there but the link to the brush is now a 404). So you'd need to upload them somewhere.

We still needed to clarify a point about the official brush package licensing policy (see https://github.com/mypaint/mypaint-brushes/commit/5adf08db45aa18a2ceeac1d5084e8e5de57caea9). Basically all brush in this package must be released in the public domain (CC0 1.0). There does not seem to be any licensing information available on the Deviantart page.

If you are the author, please be aware that requesting your brushes to be in this package means for releasing them as public domain. If you are not the author, please beforehand requesting inclusion, ensure they are ok with it by either finding a source where they already said it was CC0 or by contacting them.

I will now close this report as any further discussion will have to be done on a new report on the new [official repo](https://github.com/mypaint/mypaint-brushes/).
