### ISSUE TITLE
Compatible to gimp?

### ISSUE THREAD

**Issue by ghost** [Jehan/mypaint-brushes#8]
Hello.

Gimp now requires mypaint-brushes but there are several projects on github with the same name or perhaps semi-identical code.

Could the main readme briefly mention whether this release is compatible - or preferred - with gimp?

It would help users who try to compile gimp from source, to get all dependencies right. mypaint-brushes is the last dependency that I need before I can compile gimp, it seems.

**Comment by Jehan** [comment]
> Gimp now requires mypaint-brushes but there are several projects on github with the same name or perhaps semi-identical code.

This one is indeed the right mypaint-brushes.

> Could the main readme briefly mention whether this release is compatible - or preferred - with gimp?

INSTALL file in GIMP repository mentions this repository. Though, if you build from repo, unless the configure script successfully runs at least once, INSTALL is not properly generated, so you have to check out INSTALL.in (if you build from tarball though, INSTALL will be right from the start).

The INSTALL.in will also tell you the branch to build (not master).

**Comment by Jehan** [comment]
Not sure why I didn't close this one earlier. Anyway since it is still opened, a short announcement: a few days ago, the repository got moved upstream at MyPaint project. So the new right repository is: https://github.com/mypaint/mypaint-brushes
